export const allmovies = [
  {
    name: 'Joker',
    year: 2019,
    imgSrc: 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    description: 'During the 1980s, a failed stand-up comedian is driven insane and turns to a life of crime and chaos in Gotham City while becoming an infamous psychopathic crime figure.',
    director: 'Todd Phillips',
    writer: 'Scott Silver',
    rating: 9.0,
    released: 'October 4, 2019',
    genre: 'Crime',
    language: 'English',
    country: 'United States',
    runtime: '2h 2m',
    actors: ['Joaquin Phoenix','Robert De Niro','Zazie Beetz'],
    awards: []
  },
  {
    name: 'The Lion King',
    year: 2019,
    imgSrc: 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/2bXbqYdUdNVa8VIWXVfclP2ICtT.jpg',
    description: 'Simba idolises his father, King Mufasa, and takes to heart his own royal destiny. But not everyone in the kingdom celebrates the new cub arrival. Scar, Mufasa brother—and former heir to the throne—has plans of his own. The battle for Pride Rock is ravaged with betrayal, tragedy and drama, ultimately resulting in Simba being exiled. With help from a curious pair of newfound friends, Simba will have to figure out how to grow up and take back what is rightfully his.',
    director: 'Jon Favreau',
    writer: 'Jon Favreau',
    rating: 4.5,
    released: 'July 19, 2019',
    genre: 'Adventure',
    language: 'English',
    country: 'United States',
    runtime: '1h 58m',
    actors: ['Donald Glover', 'James Earl Jones', 'Chiwetel Ejiofor'],
    awards: []
  },
  {
    name: 'Maleficent',
    year: 2019,
    imgSrc: 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/vloNTScJ3w7jwNwtNGoG8DbTThv.jpg',
    description: 'Maleficent and her goddaughter Aurora begin to question the complex family ties that bind them as they are pulled in different directions by impending nuptials, unexpected allies, and dark new forces at play.',
    director: 'Joachim Rønning',
    writer: 'Joachim Rønning',
    rating: 6.0,
    released: 'October 18, 2019',
    genre: 'Fantasy',
    runtime: '1h 58m',
    language: 'English',
    country: 'United States',
    actors: ['Angelina Jolie', 'Elle Fanning', 'Michelle Pfeiffer'],
    awards: []
  },
  {
    name: 'Terminator',
    year: 2019,
    imgSrc: 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/vqzNJRH4YyquRiWxCCOH0aXggHI.jpg',
    description: 'More than two decades have passed since Sarah Connor prevented Judgment Day, changed the future, and re-wrote the fate of the human race. Dani Ramos (Natalia Reyes) is living a simple life in Mexico City with her brother (Diego Boneta) and father when a highly advanced and deadly new Terminator – a Rev-9 (Gabriel Luna) – travels back through time to hunt and kill her.',
    director: 'Tim Miller',
    writer: 'Tim Miller',
    rating: 9.0,
    released: 'November 1 2019',
    genre: 'Sci-Fi',
    runtime: '2h 8m',
    language: 'English',
    country: 'United States',
    actors: ['Natalia Reyes', 'Mackenzie Davis', 'Linda Hamilton'],
    awards: []
  },
  {
    name: 'El Camino',
    year: 2019,
    imgSrc: 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/ePXuKdXZuJx8hHMNr2yM4jY2L7Z.jpg',
    description: 'In the wake of his dramatic escape from captivity, Jesse Pinkman must come to terms with his past in order to forge some kind of future.',
    director: 'Vince Gilligan',
    writer: 'Vince Gilligan',
    rating: 4.0,
    released: 'October 11, 2019',
    genre: 'Crime',
    runtime: '2h 3m',
    language: 'English',
    country: 'United States',
    actors: ['Aaron Paul', 'Jesse Plemons'],
    awards: []
  },
  {
    name: 'Toy Story 4',
    year: 2019,
    imgSrc: 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/w9kR8qbmQ01HwnvK4alvnQ2ca0L.jpg',
    description: 'Woody has always been confident about his place in the world and that his priority is taking care of his kid, whether that is Andy or Bonnie. But when Bonnie adds a reluctant new toy called "Forky" to her room, a road trip adventure alongside old and new friends will show Woody how big the world can be for a toy.',
    director: 'Josh Cooley',
    writer: 'Josh Cooley',
    rating: 8.0,
    released: 'June 11, 2019',
    genre: 'Animation',
    language: 'English',
    country: 'United States',
    actors: ['Tom Hanks', 'Annie Potts', 'Tim Allen'],
    awards: []
  },
  {
    name: 'Fast & Furious',
    year: 2019,
    imgSrc: 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/keym7MPn1icW1wWfzMnW3HeuzWU.jpg',
    description: 'A spinoff of The Fate of the Furious, focusing on Johnsons US Diplomatic Security Agent Luke Hobbs forming an unlikely alliance with Stathams Deckard Shaw.',
    director: 'David Leitch',
    writer: 'David Leitch',
    rating: 5.0,
    released: 'July 13, 2019',
    genre: 'Action',
    runtime: '2h 16m',
    language: 'English',
    country: 'United States',
    actors: ['Dwayne Johnson', 'Jason Statham', 'Idris Elba'],
    awards: []
  },
  {
    name: 'Harry Potter',
    year: 2001,
    imgSrc: 'https://image.tmdb.org/t/p/w600_and_h900_bestv2/dCtFvscYcXQKTNvyyaQr2g2UacJ.jpg',
    description: "Harry Potter has lived under the stairs at his aunt and uncle's house his whole life. But on his 11th birthday, he learns he's a powerful wizard -- with a place waiting for him at the Hogwarts School of Witchcraft and Wizardry. As he learns to harness his newfound powers with the help of the school's kindly headmaster, Harry uncovers the truth about his parents' deaths -- and about the villain who's to blame.",
    director: 'Chris Columbus',
    writer: 'Chris Columbus',
    rating: 8.0,
    released: 'November 14 2001',
    genre: 'Fantasy',
    runtime: '2h 36min',
    language: 'English',
    country: 'United States',
    actors: ['Daniel Radcliffe', 'Rupert Grint', 'Emma Watson'],
    awards: []
  }
];

/*
Copyright Google LLC. All Rights Reserved.
Use of this source code is governed by an MIT-style license that
can be found in the LICENSE file at http://angular.io/license
*/
